"""update table and column names

Revision ID: 074830e8ae4b
Revises: 54258f32c442
Create Date: 2024-02-21 17:11:12.451147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074830e8ae4b'
down_revision = '54258f32c442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
