"""update table names

Revision ID: 177914085da8
Revises: d9b363f11587
Create Date: 2024-02-21 18:17:29.086414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177914085da8'
down_revision = 'd9b363f11587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
